# Generated by Django 3.1.2 on 2020-12-09 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipousuario',
            old_name='descripción',
            new_name='descripcion',
        ),
    ]
