# Generated by Django 3.1.2 on 2020-12-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_biografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen_auto',
            field=models.ImageField(null=True, upload_to='bd/usuarios'),
        ),
    ]
