# Generated by Django 3.1.2 on 2020-12-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_auto_20201209_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(default='bd/usuarios/no-img.jpg', upload_to='bd/usuarios'),
        ),
    ]
