# Generated by Django 2.2.17 on 2020-12-07 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Casas',
            new_name='Casa',
        ),
    ]
