# Generated by Django 2.2.17 on 2020-12-07 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201207_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casa',
            options={'verbose_name_plural': 'cases'},
        ),
    ]
