# Generated by Django 2.2.17 on 2020-12-07 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201207_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casa',
            options={},
        ),
    ]
