# Generated by Django 2.2.17 on 2020-12-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201207_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='descripcion',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
