# Generated by Django 2.2.17 on 2020-12-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201207_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='foto',
            field=models.ImageField(upload_to='casas/'),
        ),
    ]
