# Generated by Django 3.1.2 on 2020-12-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='bd/autos')),
                ('marca', models.CharField(max_length=70)),
                ('modelo', models.CharField(max_length=70)),
                ('descripcion', models.CharField(max_length=300)),
            ],
        ),
    ]
