# Generated by Django 3.1.2 on 2020-12-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
