# Generated by Django 3.1.2 on 2020-12-09 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_auto_20201209_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='descripcion',
        ),
    ]
