# Generated by Django 3.1.2 on 2020-12-10 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_auto_20201209_1824'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auto',
        ),
    ]
