# Generated by Django 3.1.2 on 2020-12-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto', '0005_delete_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='bd/autos')),
                ('marca', models.CharField(max_length=70)),
                ('modelo', models.CharField(max_length=70)),
                ('anno', models.CharField(max_length=4)),
                ('velocidad_partida', models.CharField(max_length=50)),
                ('velocidad_maxima', models.DecimalField(decimal_places=2, max_digits=6)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
    ]
