# Generated by Django 3.1.2 on 2020-12-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0014_auto_20201210_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competencia',
            name='anno',
        ),
        migrations.AddField(
            model_name='competencia',
            name='victorias',
            field=models.IntegerField(default=0),
        ),
    ]
