# Generated by Django 3.1.2 on 2020-12-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0015_auto_20201210_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='historia',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
