# Generated by Django 3.1.2 on 2020-12-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0016_marca_historia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='historia',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
