# Generated by Django 3.1.2 on 2020-12-11 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0018_auto_20201210_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagenes_Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='bd/marcas')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.marca')),
            ],
        ),
    ]
